product: ucs
release: "5.0"
version: [0]
scope: ucs_5.0-0-errata5.0-0
src: univention-directory-replication
fix: 13.0.2-2A~5.0.0.202106160942
desc: |
 This update addresses the following issue:
 * Applying a `failed.ldif` has been repaired. This was broken due to the
   Python 3 migration.
bug: [53430]
erratum: 20
announced: 2021-06-23
